package com.example.CrickBuzz.service;

import com.example.CrickBuzz.converter.PlayerConverter;
import com.example.CrickBuzz.dto.request.PlayerRequest;
import com.example.CrickBuzz.dto.response.PlayerResponse;
import com.example.CrickBuzz.exeptions.PlayerNotFoundException;
import com.example.CrickBuzz.model.Player;
import com.example.CrickBuzz.model.enums.Speciality;
import com.example.CrickBuzz.repository.PlayerRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import java.util.ArrayList;
import java.util.List;
import java.util.Optional;

@Service
public class PlayerService {

    @Autowired
    PlayerRepository playerRepository;


    //here data type is player there are some attributes which are autogenerated we are passing the player without those attributes
    //and .save function saving the player along with those autogenerated attributes like our id and time
    public PlayerResponse addPlayer(PlayerRequest playerRequest){
     Player player = PlayerConverter.PlayerDtoToPlayer(playerRequest);
       Player savedPlayer =  playerRepository.save(player);

       //but i want to written the player response so we create the separete converter for player responsse
        return PlayerConverter.PlayerToPlayerResponse(savedPlayer);
    }

    public List<PlayerResponse> FindPlayerGreaterThenAge(int age){
        List<Player> players = playerRepository.findByAgeGreaterThan(age);
        //for storing the list we need arraylist
        List<PlayerResponse> playerResponses = new ArrayList<>();
        for(Player player:players){
            playerResponses.add(PlayerConverter.PlayerToPlayerResponse(player));//here we need to add player response so traverse in the list get the player and convert to player response
        }
        return playerResponses;
    }

    public List<PlayerResponse> playerByAgeGreaterThanAndSpeciality(int age, Speciality speciality) {
        List<Player> players = playerRepository.playerByAgeGreaterThanAndSpeciality(age, speciality);
        List<PlayerResponse> playerResponses = new ArrayList<>();
        for(Player player:players){
            playerResponses.add(PlayerConverter.PlayerToPlayerResponse(player));//here we need to add player response so traverse in the list get the player and convert to player response
        }
        return playerResponses;
    }

    public Player getPlayer(int playerId) {
       Optional<Player> Optionalplayer = playerRepository.findById(playerId);
        if(Optionalplayer.isEmpty()){
            throw new PlayerNotFoundException("invalid PlayerId");
        }

        return Optionalplayer.get();
    }
}
